# Generated by Django 3.2.6 on 2021-08-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=10)),
                ('last_observation', models.DateTimeField(auto_now=True)),
                ('temperature', models.CharField(max_length=50)),
                ('wind', models.CharField(max_length=50)),
            ],
        ),
    ]
